# Restart webpack-dev-server if you make changes here
default: &default
  enabled: true
  protocol: http
  host: localhost
  port: 8081

development:
  <<: *default

test:
  <<: *default
  enabled: false

production:
  <<: *default
  protocol: https
  enabled: false
