# Restart webpack-dev-server if you make changes here
default: &default
  # Optional HMR support - https://webpack.js.org/concepts/hot-module-replacement/
  # Set true if you need HMR support
  hot: true
  protocol: http
  host: localhost
  port: 8080

development:
  <<: *default

test:
  <<: *default
  enabled: false

production:
  <<: *default
  enabled: false
  # Useful for cloud9
  host: 0.0.0.0
  port: 80
  protocol: https
