# Restart webpack-watcher or webpack-dev-server if you make changes here
default: &default
  # entry directory for webpack, uses same directory name when emiting builds inside output folder
  entry: entries
  # custom config file to add/update weback config used by webpacker
  # this file should be placed under config/webpack/[name.js]
  # ex: config/webpack/webpacker.config.js
  customConfig: webpacker.config.js
  output: public
  manifest: manifest.json
  source: app/assets/javascript
  extensions:
    - .coffee
    - .js
    - .jsx
    - .ts
    - .vue
    - .sass
    - .scss
    - .css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default

test:
  <<: *default
  manifest: manifest-test.json

production:
  <<: *default
