# Restart webpack-watcher or webpack-dev-server if you make changes here
default: &default
  config: config/webpack
  entry: entries
  output: public
  manifest: manifest.json
  node_modules: node_modules
  source: app/assets/javascript
  extensions:
    - .coffee
    - .js
    - .jsx
    - .ts
    - .vue
    - .sass
    - .scss
    - .css
    - .png
    - .svg
    - .gif
    - .jpeg

development:
  <<: *default

test:
  <<: *default
  manifest: manifest-test.json

production:
  <<: *default
