# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: app/assets/javascript
  source_entry_path: entries
  public_output_path: entries
  cache_path: tmp/cache/webpacker

  # Additional paths webpack should lookup modules
  # ['app/assets', 'engine/foo/app/assets']
  resolved_paths: []

  extensions:
    - .elm
    - .coffee
    - .erb
    - .js
    - .jsx
    - .ts
    - .vue
    - .sass
    - .scss
    - .css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default
  compile: true
  dev_server:
    host: localhost
    port: 8080
    https: false

test:
  <<: *default
  compile: true
  public_output_path: packs-test

production:
  <<: *default

  # Production demands on precompilation of packs prior to booting for performance.
  compile: false
